WEATHER_API_CORRECT_DATA = {
    "coord": {"lon": 2.32, "lat": 48.858},
    "weather": [
        {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
    ],
    "base": "stations",
    "main": {
        "temp": 8.19,
        "feels_like": 7.03,
        "temp_min": 6.07,
        "temp_max": 9.42,
        "pressure": 998,
        "humidity": 86,
    },
    "visibility": 10000,
    "wind": {"speed": 2.06, "deg": 220},
    "clouds": {"all": 0},
    "dt": 1710099501,
    "sys": {
        "type": 2,
        "id": 2012208,
        "country": "FR",
        "sunrise": 1710051241,
        "sunset": 1710092882,
    },
    "timezone": 3600,
    "id": 6545270,
    "name": "Palais-Royal",
    "cod": 200,
}

WEATHER_API_INCORRECT_DATA = {
    "coord": {"lon": 2.32, "lat": 48.858},
    "weather": [{"id": 800, "description": "clear sky", "icon": "01n"}],
    "base": "stations",
    "main": {
        "temp": 8.19,
        "temp_min": 6.07,
        "temp_max": 9.42,
        "pressure": 998,
        "humidity": 86,
    },
    "visibility": 10000,
    "wind": {"speed": 2.06, "deg": 220},
    "clouds": {"all": 0},
    "dt": 1710099501,
    "sys": {
        "type": 2,
        "id": 2012208,
        "country": "FR",
        "sunrise": 1710051241,
        "sunset": 1710092882,
    },
    "timezone": 3600,
    "id": 6545270,
    "cod": 200,
}

GEOCODIND_API_DIRECT_DATA = [
    {
        "name": "Paris",
        "local_names": {
            "za": "Bahliz",
            "mi": "Parī",
            "no": "Paris",
            "kv": "Париж",
            "uz": "Parij",
            "li": "Paries",
            "mr": "पॅरिस",
            "gu": "પૅરિસ",
            "es": "París",
            "ml": "പാരിസ്",
            "sq": "Parisi",
            "ba": "Париж",
            "hu": "Párizs",
            "ku": "Parîs",
            "lv": "Parīze",
            "hy": "Փարիզ",
            "ps": "پاريس",
            "ko": "파리",
            "sk": "Paríž",
            "bn": "প্যারিস",
            "yi": "פאריז",
            "la": "Lutetia",
            "sl": "Pariz",
            "el": "Παρίσι",
            "gv": "Paarys",
            "bo": "ཕ་རི།",
            "eo": "Parizo",
            "bs": "Pariz",
            "uk": "Париж",
            "or": "ପ୍ୟାରିସ",
            "am": "ፓሪስ",
            "kk": "Париж",
            "ur": "پیرس",
            "et": "Pariis",
            "be": "Парыж",
            "fy": "Parys",
            "os": "Париж",
            "gn": "Parĩ",
            "vi": "Paris",
            "te": "పారిస్",
            "fi": "Pariisi",
            "tl": "Paris",
            "cs": "Paříž",
            "lb": "Paräis",
            "tt": "Париж",
            "ru": "Париж",
            "ne": "पेरिस",
            "nl": "Parijs",
            "ht": "Pari",
            "th": "ปารีส",
            "km": "ប៉ារីស",
            "sc": "Parigi",
            "fr": "Paris",
            "ka": "პარიზი",
            "ga": "Páras",
            "ha": "Pariis",
            "mn": "Парис",
            "is": "París",
            "sr": "Париз",
            "wo": "Pari",
            "sh": "Pariz",
            "my": "ပါရီမြို့",
            "fa": "پاریس",
            "lt": "Paryžius",
            "sv": "Paris",
            "gl": "París",
            "de": "Paris",
            "hi": "पैरिस",
            "ar": "باريس",
            "cv": "Парис",
            "ln": "Pari",
            "pl": "Paryż",
            "wa": "Paris",
            "tk": "Pariž",
            "tg": "Париж",
            "ja": "パリ",
            "he": "פריז",
            "pa": "ਪੈਰਿਸ",
            "ug": "پارىژ",
            "zh": "巴黎",
            "oc": "París",
            "yo": "Parisi",
            "co": "Parighji",
            "ca": "París",
            "ky": "Париж",
            "hr": "Pariz",
            "mk": "Париз",
            "br": "Pariz",
            "zu": "IParisi",
            "kn": "ಪ್ಯಾರಿಸ್",
            "bg": "Париж",
            "ta": "பாரிஸ்",
            "it": "Parigi",
            "af": "Parys",
            "eu": "Paris",
            "so": "Baariis",
            "cu": "Парижь",
            "an": "París",
        },
        "lat": 48.8588897,
        "lon": 2.3200410217200766,
        "country": "FR",
        "state": "Ile-de-France",
    }
]

GEOCODIND_API_ZIP_DATA = {
    "zip": "75007",
    "name": "Paris",
    "lat": 48.8534,
    "lon": 2.3488,
    "country": "FR",
}
