name: Release
on:
  push:
    tags:
      - "*"
permissions:
  contents: read
jobs:
  codequality_and_testing:
    uses: ./.github/workflows/codequality_and_testing.yml
  deploy:
    needs: [codequality_and_testing]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
